# -*- coding: utf-8 -*-
"""Jucélio Brandão Gonçalves Junior Exercicio 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NGLqTANf_1xLmQQqQlMEdJxyoWfngL-U

Exercício 1 semana 2
"""

import pandas as pd

footballStadiums = pd.read_csv("https://drive.google.com/u/3/uc?id=1Z8HNz979cgf40LGw8FoNSWew-2xFZXOr&export=download", encoding='latin-1')

"""
1 - Leia a Tabela do arquivo CSV para o seu notebook"""

footballStadiums

"""2 – Crie uma instrução para visualizar as primeiras 5 linhas da tabela

"""

footballStadiums.head(5)

"""3 - Crie uma instrução para visualizar as últimas 8 linhas da tabela"""

footballStadiums.tail(8)

"""4 - Crie uma instrução para visualizar as 10 primeiras linhas dos atributos: """

footballStadiums.head(10)[['Stadium', 'Country', 'Population']]

"""5 - Crie uma instrução para visualizar a coluna: HomeTeams"""

footballStadiums[['HomeTeams']]