# -*- coding: utf-8 -*-
"""Jucélio Brandão Gonçalves Junior Atividade 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kh3HPh8ybl-GFS21-ZiNGZK3bDKdJ-o_

Atividade 4
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
notas = pd.read_csv("https://drive.google.com/u/3/uc?id=1sV0JD4aSx0brbH_Jmz3ibrjdLhPsepGn&export=download")

"""Exercicio 1"""

corrP1P2 = notas['Prova 1'].corr(notas['Prova 2']).round(2)
corrP1T = notas['Prova 1'].corr(notas['Trabalho']).round(2)
corrP2T = notas['Prova 2'].corr(notas['Trabalho']).round(2)
print('Correlação entre:')
print('Prova 1 e Prova 2:', corrP1P2)
print('Prova 1 e Trabalho:', corrP1T)
print('Prova 2 e Trabalho:', corrP2T)

higherCorr = 0

if corrP1P2 > corrP1T and corrP1P2 > corrP2T:
  higherCorr = 'Prova 1 e Prova 2 com:', corrP1P2
elif corrP1T > corrP1P2 and corrP1T > corrP2T:
  higherCorr = 'Prova 1 e Trabalho com:', corrP1T
else:
  higherCorr = 'Prova 2 e Trabalho com:', corrP2T

print('O par mais fortemente correlacionado é:', higherCorr)

"""Exercicio 2

"""

print(notas, '\n', notas[['Prova 1']])
print('Correlação entre Trabalho e Prova 1:', notas['Trabalho'].corr(notas['Prova 1']).round(2))
print('Podemos concluir que é pouco provavavel que as notas da Prova 1 tenham impacto nas notas do Trabalho')

"""Exercicio 3

"""

notas
a, b = np.polyfit(x=notas['Prova 1'], y=notas['Prova 2'], deg = 1)
print('valor de a:', a, '\n','valor de b:', b)

a = 1.010
b = 19.332
x = np.arange(0,101)
y = a*x+b
plt.plot(x,y,'r')

y = a*65+b
print('O valor da predição de 65 será:', y)

"""Exercicio 4"""

notas

a, b = np.polyfit(x=notas['Prova 1'], y=notas['Prova 2'], deg = 1)
print('Valor de a:', a)
print('Valor de b:', b)

a = 1.010
b = 19.332
x = np.arange(0,101)
y = a*x+b
plt.plot(x,y,'r')

import random as rd
n = rd.randint(0, 100)
n

y = a*n+b
print('O valor da predição de n será:', y)